### ISSUE TITLE
I how did that happen.

### ISSUE THREAD

**Issue by liuchangxing** [thtliife/grammar-tab-colors#3]
![qq 20160922232507](https://cloud.githubusercontent.com/assets/22342099/18754648/0025d728-811c-11e6-9cd0-15e56ec727e7.png)
Cannot set!

**Comment by liuchangxing** [comment]
Oh, sorry  sorry.

I just made a mistake, but it is now resolved.

**Comment by thtliife** [comment]
Glad you worked it out :)
