### ISSUE TITLE
Custom grammar  not detected

### ISSUE THREAD

**Issue by LeMinaw** [thtliife/grammar-tab-colors#4]
This custom grammar package : [https://github.com/Ramalus/language-kivy](url) is not detected by grammar-tab-colors' config.

**Comment by thtliife** [comment]
Thanks LeMinaw, I'll look into it today

**Comment by thtliife** [comment]
Ok, Please try updating to v0.2.1
Should now work properly with custom grammars

**Comment by thtliife** [comment]
Can you update to v0.2.2 and try please?

**Comment by LeMinaw** [comment]
Fixed. Thanks a lot !
