### ISSUE TITLE
Non-blocking error message

### ISSUE THREAD

**Issue by LeMinaw** [thtliife/grammar-tab-colors#5]
After restarting reloading the Atom window : 

```
Uncaught Error:
EEXIST: file already exists, mkdir '/home/user/.atom/packages/grammar-tab-colors/styles' fs.js:842 
Tracktrace:
at Error (native)
at Object.fs.mkdirSync (fs.js:842:18)
at /home/user/.atom/packages/grammar-tab-colors/lib/grammar-tab-colors-utils.js:194:10
```

Just FYI, there's actually no problem in using atom or your extension.

**Comment by thtliife** [comment]
Hi LeMinaw,
I am unable to reproduce this error.
Could you possibly give me steps to reproduce?

**Comment by thtliife** [comment]
I think I found it, should be fixed in latest version
